### ISSUE TITLE
Remove hugo theme default posts

### ISSUE THREAD

**Issue by fanny** [FannyVieira/personal-blog#1]
a

**Comment by FannyVieira** [comment]
asdlçhfeopffffffffffffffffffff

**Comment by FannyVieira** [comment]
sdfgsagdfg

**Comment by FannyVieira** [comment]
erewrw

**Comment by FannyVieira** [comment]
asdsd

**Comment by FannyVieira** [comment]
asr

**Comment by FannyVieira** [comment]
ttgh

**Comment by FannyVieira** [comment]
cjhodhofe

**Comment by FannyVieira** [comment]
hey fanny, should be right.

**Comment by FannyVieira** [comment]
hey, one more night.

**Comment by FannyVieira** [comment]
xvhtyhtyj

**Comment by FannyVieira** [comment]
gdgdfg

**Comment by FannyVieira** [comment]
ss

**Comment by FannyVieira** [comment]
Hello darling! :)

**Comment by FannyVieira** [comment]
Hello my darling! :D

**Comment by FannyVieira** [comment]
a

**Comment by FannyVieira** [comment]
w

**Comment by vinifarias** [comment]
Testing...

**Comment by FannyVieira** [comment]
gfd

**Comment by FannyVieira** [comment]
fuf

**Comment by FannyVieira** [comment]
testers

**Comment by vinifarias** [comment]
Deu certo ?

**Comment by FannyVieira** [comment]
tente de novo, my angel

**Comment by FannyVieira** [comment]
ff

**Comment by FannyVieira** [comment]
Try again, my angel, please!! :relaxed:

**Comment by fanny** [comment]
Try again, my angel, please!! :relaxed: :octocat: :worried: :woman_cartwheeling: :woman_astronaut:

**Comment by vinifarias** [comment]
Testing...

**Comment by FannyVieira** [comment]
Thank u :heart_decoration:

**Comment by fanny** [comment]
Thank u :heart_decoration:

**Comment by FannyVieira** [comment]
that's life...

**Comment by FannyVieira** [comment]
That's life :)

**Comment by FannyVieira** [comment]
YESSS

**Comment by vinifarias** [comment]
para mais n...

**Comment by vinifarias** [comment]
Amei isso, toda vez que tu n me responder comento aqui <3

**Comment by fanny** [comment]
KKKKKKKKKKKKKKKKKKKK

**Comment by fanny** [comment]
É porque pra eu testar, eu tenho que comentar, afe. Mas vou parar, porque preciso estudar pras coisas da universidade, queria só deixar umas coisas prontas

**Comment by fanny** [comment]
Depois abro o repo que tem o códigokkkkkk, foi divertido fazer

**Comment by vinifarias** [comment]
Imagino kkkkkkkkk
